[project]
name = "advent-of-code"
version = "0.1.0"
description = "Advent of Code"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
]
